// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent event types for session lifecycle
 */
export type AgentEvent = { "type": "sessionCreated", "payload": { sessionId: string, sessionName: string, agentType: string, workspacePath: string | null, } } | { "type": "sessionDeleted", "payload": { sessionId: string, } } | { "type": "dialogTurnStarted", "payload": { sessionId: string, turnId: string, turnIndex: number, userInput: string, } } | { "type": "dialogTurnCompleted", "payload": { sessionId: string, turnId: string, } } | { "type": "dialogTurnCancelled", "payload": { sessionId: string, turnId: string, } } | { "type": "dialogTurnFailed", "payload": { sessionId: string, turnId: string, error: string, } } | { "type": "tokenUsageUpdated", "payload": { sessionId: string, turnId: string, modelId: string, inputTokens: number, outputTokens: number, totalTokens: number, } } | { "type": "sessionStateChanged", "payload": { sessionId: string, newState: string, } };
