// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text chunk data structure for streaming
 */
export type TextChunk = { sessionId: string, turnId: string, roundId: string, text: string, timestamp: number, contentType: string | null, isComplete: boolean, };
