// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool event types
 */
export type ToolEventType = "started" | "params_detected" | "params_complete" | "completed" | "failed" | "progress" | "stream_chunk" | "confirmation_needed";
