// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolEventType } from "./ToolEventType";

/**
 * Tool event for tracking tool execution
 */
export type ToolEvent = { sessionId: string, turnId: string, toolId: string, toolName: string, eventType: ToolEventType, params: unknown, result: unknown, error: string | null, durationMs: number | null, };
