// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache statistics
 */
export type CacheStats = { totalSessions: number, totalEvents: number, dbSizeBytes: number, };
